### ISSUE TITLE
Colocar cursor not allowed en botones disabled

### ISSUE THREAD

**Issue by fedejuret** [attrix182/CssFramework#1]
Que al pasar el cursor sobre un botón disabled, se podría poner alguna especie de cursor que indique que no está habilitado.
![image](https://user-images.githubusercontent.com/62821179/133936954-677e2d4c-618c-4fe3-ba51-16ae574987ac.png)

**Comment by attrix182** [comment]
Buena idea!, agregue dentro de propiedades clases que modifican el cursor:
![Captura de pantalla 2021-09-19 202756](https://user-images.githubusercontent.com/44885834/133946307-27190fe6-fcda-4ff0-b1fc-27a76b6c655d.jpg)

**Comment by fedejuret** [comment]
Excelente!
